# Generated by Django 3.2.9 on 2021-12-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(default='radio', max_length=255)),
                ('answer', models.JSONField()),
                ('point', models.IntegerField()),
                ('Rightanswer', models.CharField(max_length=255)),
            ],
        ),
    ]
