# Generated by Django 3.2.9 on 2021-12-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('lesson', models.JSONField(encoder='')),
                ('create_on', models.DateTimeField()),
                ('create_by', models.CharField(max_length=255)),
            ],
        ),
    ]
