# Generated by Django 3.2.9 on 2022-01-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_on',
            field=models.DateField(),
        ),
    ]
