# Generated by Django 4.0.2 on 2022-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('courseid', models.IntegerField()),
                ('point', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
