# Generated by Django 3.2.9 on 2022-01-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_class_a_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_a',
            name='created_on',
            field=models.DateField(),
        ),
    ]
