# Generated by Django 3.2.9 on 2021-12-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('quiz', models.JSONField()),
                ('create_on', models.DateField()),
            ],
        ),
    ]
