# Generated by Django 3.2.9 on 2022-01-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='create_by',
            field=models.IntegerField(default=14),
        ),
    ]
