# Generated by Django 3.2.9 on 2021-12-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_byID',
            field=models.IntegerField(default=14),
        ),
    ]
