# Generated by Django 3.2.9 on 2021-12-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_byid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_byID',
            field=models.IntegerField(),
        ),
    ]
