# Generated by Django 3.2.9 on 2021-12-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_created_byid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_byID',
        ),
    ]
