# Generated by Django 4.0.2 on 2022-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='exam',
            name='nameExam',
            field=models.CharField(default='Exam', max_length=255),
        ),
    ]
