# Generated by Django 4.0.2 on 2022-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_quiz_alter_exam_nameexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.IntegerField(default=0),
        ),
    ]
